menu:
    文章: /
    归档: /archives/
    招聘: /categories/hr/
    求职: /categories/job/
    英雄榜: /about/

widgets:
- category
- tag
- tagcloud
- archive

# count
show_count: true
favicon: /images/favicon.ico
logo: /images/logo.png

# Comment
# e.g disqus: seansun
disqus:
# duoshuo: bubuzou

# Analytics
# google-analytics:
# ga: UA-65933410-1

# Copyright Infomation
startyear: 2016
